# Generated by Django 5.1.2 on 2024-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, null=True)),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("major", models.CharField(max_length=200, null=True)),
                ("level", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
